///<summary>
/// Author:    Aaron Morgan
/// Partner:   None
/// Date:      3/29/2020
/// Course:    CS 3500, University of Utah, School of Computing 
/// Copyright: CS 3500 and Aaron Morgan
/// 
/// I, Aaron Morgan, certify that I wrote this code from scratch and did not copy it in part
/// or in whole from another source.
/// 
///</summary>

using Microsoft.Extensions.Logging;
using System;

namespace FileLogger
{

    /// <summary>
    /// The wrapper class to be used for the CustomFileLogger.
    /// </summary>
    public class CustomFileLogProvider : ILoggerProvider
    {
        private CustomFileLogger logger;

        /// <summary>
        /// Creates a custom logger that writes a specific Log message (generated by CustomFileLogger).
        /// </summary>
        /// <param name="categoryName">This is parameter should be provided by the Services Builder.</param>
        /// <returns></returns>
        public ILogger CreateLogger(string categoryName)
        {
            logger = new CustomFileLogger(categoryName);
            return logger;
        }

        /// <summary>
        /// The Dispose method to close the writer after it has finished writing to the file.
        /// </summary>
        public void Dispose()
        {
            logger.Dispose();
        }
    }
}
